name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # täglich um 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: last_7_days
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_LANGUAGE: true
          SHOW_EDITORS: true
          SHOW_OS: true
