name: Update README with WakaTime

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: WakaTime Readme Update
    runs-on: ubuntu-latest

    steps:
      - name: Use WakaTime GitHub Action
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LANGUAGE: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_TIMEZONE: "True"
          SHOW_COMMIT: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          LOCALE: "en"
